pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Plan Terraform') {
      steps {
        sh 'terraform init'
        sh 'terraform plan -out=tfplan'
      }
    }
    stage('Apply Terraform') {
      steps {
        input 'Apply Terraform?'
        sh 'terraform apply "tfplan" -var-file="secret.tfvars"'
      }
    }
    stage('Configure Instance with Ansible') {
      steps {
        script {
          def ips = sh(script: 'terraform output -raw instance_ip', returnStdout: true).trim()
          writeFile(file: 'ansible/hosts', text: "$ips ansible_user=ec2-user ansible_ssh_private_key_file=/path/to/key.pem")
        }
        sh 'ansible-playbook -i ansible/hosts ansible/playbook.yml'
      }
    }
  }
  post {
    always {
      sh 'terraform destroy -auto-approve'
    }
  }
}
