name: Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  packages: write
  contents: read

defaults:
  run:
    working-directory: java-maven/test-app-javamaven

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '17.0.12'
  #         distribution: 'temurin'

  #     - name: Run Maven Lint
  #       run: mvn checkstyle:check

  test:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.12'
          distribution: 'temurin'

      - name: Install dependencies and run tests
        run: mvn clean test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.12'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 and configure Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github  # Doit correspondre à l'id dans pom.xml
          server-username: clemuscle  # Nom d'utilisateur GitHub
          server-password: ${{ secrets.GITHUB_TOKEN }}  # Token GitHub
          settings-path: ${{ github.workspace }}

      - name: Build and Deploy
        run: mvn clean deploy --settings ${{ github.workspace }}/settings.xml

      - name: Test artifact
        run: echo "Testing artifact..." # Remplace cette étape avec des tests supplémentaires si nécessaires