name: Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 11
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17.0.12'

      - name: Run Maven Lint
        run: mvn checkstyle:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 11
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17.0.12'

      - name: Install dependencies and run tests
        run: mvn clean test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 11
        uses: actions/setup-java@v4.3.0


      - name: Build project
        run: mvn clean package

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 11
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17.0.12'
          distribution: 'jdk'

      - name: Build project
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Test artifact
        run: echo "Testing artifact..." # Remplace cette étape avec des tests supplémentaires si nécessaires